### ISSUE TITLE
More middleware-like approach

### ISSUE THREAD

**Issue by bramdevries** [madewithlove/margaret-fetcher#2]
Currently the promises that handle a request are hard coded in the package, it would be nice if these promises were configurable somewhere. For example:

``` javascript
class AppRequest extends AbstractRequest
{
    constructor() {
       super();

       // Set the globally
       this.middlewares = [
           ::this.refreshAccessToken,
           ::this.parseResponse,
       ];
    }

    refreshAccessToken(response) {
         // Logic to store the `Authorization` header 
     }
}
```

Could also do it per request:

``` javascript
Request.withMiddlewares([::thisParseResponse]).show(1)
```

**Comment by Anahkiasen** [comment]
I like it, think that would be more flexible indeed, plus that way you could add custom one per request class and add them to the stack or per request, etc
